on:
  push:
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
    - master          # triggers on pushes that contain changes in master
    - feature/*

name: Build and Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1

    - name: npm install, build, and test
      id: build
      run: |
        npm install
        npm run build --if-present
        npm test

    - name: 'Sending SMS Notification'
      if: failure()
      uses: twilio-labs/actions-sms@v1
      with:
        fromPhoneNumber: ${{ secrets.FROM_NUMBER }}
        toPhoneNumber: ${{ secrets.TO_NUMBER }}
        message: 'Error encountered in Weekly Radar build.'
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
        TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}